language: python

sudo: required

matrix:
  include:
  - os: linux
    python: "2.7"
  - os: linux
    python: "3.6"
  - os: linux
    python: "3.7"
  - os: osx
    python: "2.7"
  - os: osx
    python: "3.6"
  - os: osx
    python: "3.7"

install:
  - sudo pip install -r requirements.txt
script:
  - wget https://github.com/daidai21/LeetCode.VIP
  - sudo ./LeetCode.VIP/install.sh
  - sudo python ~/.LeetCode.VIP/tests.py
